openapi: 3.0.3
info:
  title: Project microservice
  description: Api specification for project microservice
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Local debug server
paths:
  /v1/projects/{projectId}:
    get:
      description: Get full project info
      operationId: getProjectInfo
      tags:
        - project
      security:
        - bearerHttpAuthentication: [ ]
      parameters:
        - $ref: "#/components/parameters/ProjectId"
      responses:
        200:
          description: "The project has been found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectInfoDto"
        403:
          description: "Project not found"
          content:
            application/json:
              schema:
                $ref: "../common/openapi.yaml#/components/schemas/ErrorDto"
        default:
          $ref: "../common/openapi.yaml#/components/responses/UnexpectedErrorResponse"
    put:
      description: Update project infor
      operationId: updateProjectInfo
      tags:
        - project
      security:
        - bearerHttpAuthentication: [ ]
      requestBody:
        $ref: "#/components/requestBodies/UpdateProjectInfoRequestBody"
      responses:
        204:
          description: "Project info updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectInfoDto"
        403:
          description: "There is no project with same ID"
          content:
            application/json:
              schema:
                $ref: "../common/openapi.yaml#/components/schemas/ErrorDto"
        default:
          $ref: "../common/openapi.yaml#/components/responses/UnexpectedErrorResponse"
    delete:
      description: Permanently delete project
      operationId: deleteProject
      tags:
        - project
      security:
        - bearerHttpAuthentication: [ ]
      parameters:
        - $ref: "#/components/parameters/ProjectId"
      responses:
        204:
          description: "The project has been deleted"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectInfoDto"
        403:
          description: "Project not found"
          content:
            application/json:
              schema:
                $ref: "../common/openapi.yaml#/components/schemas/ErrorDto"
        default:
          $ref: "../common/openapi.yaml#/components/responses/UnexpectedErrorResponse"
  /v1/workspaces/{workspaceId}/projects:
    post:
      description: Create project with required information
      operationId: postProject
      tags:
        - project
      security:
        - bearerHttpAuthentication: [ ]
      requestBody:
        $ref: "#/components/requestBodies/CreateProjectRequestBody"
      responses:
        200:
          description: "Project created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectInfoDto"
        default:
          $ref: "../common/openapi.yaml#/components/responses/UnexpectedErrorResponse"

components:
  parameters:
    ProjectId:
      name: projectId
      in: path
      description: ID of a project
      required: true
      schema:
        type: integer
        example: "3746287468"
    WorkspaceId:
      name: workspaceId
      in: path
      description: ID of a workspace
      required: true
      schema:
        type: integer
        example: "3746287468"

  requestBodies:
    CreateProjectRequestBody:
      description: Request to create a project
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateProjectRequest"
    UpdateProjectInfoRequestBody:
      description: Request to update a project
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdateProjectRequest"

  schemas:
    ProjectInfoDto:
      description: Project information
      type: object
      properties:
        id:
          description: "ID of the project"
          type: integer
          example: 7438546582
        name:
          description: "Project name, which identifies the project to the user"
          type: string
          example: "eclipto-backend"
        description:
          description: "A project description that provides more detailed information about the project"
          type: string
          example: "Project about microservice based eclipto backend project, that implement api-gateway pattern and ..."
        lead_id:
          description: "Project lead user id"
          type: integer
          example: "3757385734"
      required:
        - id
        - name
        - lead_id
    CreateProjectRequest:
      description: Request schema to create a project
      properties:
        name:
          description: "Project name, which identifies the project to the user"
          type: string
          example: "eclipto-backend"
        description:
          description: "A project description that provides more detailed information about the project"
          type: string
          example: "Project about microservice based eclipto backend project, that implement api-gateway pattern and ..."
        lead_id:
          description: "Project lead user id"
          type: integer
          example: "3757385734"
      required:
        - name
        - lead_id
    UpdateProjectRequest:
      description: Request schema to update a project
      properties:
        name:
          description: "Project name, which identifies the project to the user"
          type: string
          example: "eclipto-backend"
        description:
          description: "A project description that provides more detailed information about the project"
          type: string
          example: "Project about microservice based eclipto backend project, that implement api-gateway pattern and ..."
        lead_id:
          description: "Project lead user id"
          type: integer
          example: "3757385734"

