/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.solurion.eclipto.task.api;

import com.solurion.eclipto.task.dto.ErrorDto;
import com.solurion.eclipto.task.dto.PostLiteTaskRequest;
import com.solurion.eclipto.task.dto.PostTaskStatusRequest;
import com.solurion.eclipto.task.dto.TaskInfoDto;
import com.solurion.eclipto.task.dto.TaskLiteDto;
import com.solurion.eclipto.task.dto.TaskStatusDto;
import com.solurion.eclipto.task.dto.UpdateTaskRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "task", description = "Operations about task")
public interface TaskApi {

    /**
     * DELETE /projects/{projectId}/tasks
     * Delete all tasks
     *
     * @param projectId ID of a project that contains tasks (required)
     * @return Tasks delete successfully (status code 204)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "deleteAllTasks",
        description = "Delete all tasks",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Tasks delete successfully"),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/projects/{projectId}/tasks",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteAllTasks(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId
    );


    /**
     * DELETE /projects/{projectId}/tasks/{taskId}
     * Permanently delete task
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param taskId ID of a task (required)
     * @return The task has been deleted (status code 204)
     *         or Task not found (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "deleteTask",
        description = "Permanently delete task",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "The task has been deleted"),
            @ApiResponse(responseCode = "403", description = "Task not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/projects/{projectId}/tasks/{taskId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteTask(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "taskId", description = "ID of a task", required = true, in = ParameterIn.PATH) @PathVariable("taskId") Long taskId
    );


    /**
     * GET /projects/{projectId}/tasks
     * Get all project tasks with full information
     *
     * @param projectId ID of a project that contains tasks (required)
     * @return Full tasks list (status code 200)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "getFullTasks",
        description = "Get all project tasks with full information",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Full tasks list", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskInfoDto.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{projectId}/tasks",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<TaskInfoDto>> getFullTasks(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId
    );


    /**
     * GET /projects/{projectId}/tasks-lite
     * Get all project tasks with lite information
     *
     * @param projectId ID of a project that contains tasks (required)
     * @return Lite tasks list (status code 200)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "getLiteTasks",
        description = "Get all project tasks with lite information",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lite tasks list", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskLiteDto.class)))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{projectId}/tasks-lite",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<TaskLiteDto>> getLiteTasks(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId
    );


    /**
     * GET /projects/{projectId}/tasks/{taskId}
     * Get full task info
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param taskId ID of a task (required)
     * @return The task has been found (status code 200)
     *         or Task not found (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "getTask",
        description = "Get full task info",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The task has been found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskInfoDto.class))
            }),
            @ApiResponse(responseCode = "403", description = "Task not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/projects/{projectId}/tasks/{taskId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<TaskInfoDto> getTask(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "taskId", description = "ID of a task", required = true, in = ParameterIn.PATH) @PathVariable("taskId") Long taskId
    );


    /**
     * POST /projects/{projectId}/tasks
     * Create task with lite information
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param postLiteTaskRequest Request to create a task (optional)
     * @return Task created successfully (status code 204)
     *         or There is no status with same ID (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "postLiteTask",
        description = "Create task with lite information",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Task created successfully"),
            @ApiResponse(responseCode = "403", description = "There is no status with same ID", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/projects/{projectId}/tasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> postLiteTask(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "PostLiteTaskRequest", description = "Request to create a task") @Valid @RequestBody(required = false) PostLiteTaskRequest postLiteTaskRequest
    );


    /**
     * POST /projects/{projectId}/tasks/statuses
     * Create tasks status
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param postTaskStatusRequest Request to create a task status (optional)
     * @return Status created successfully (status code 204)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "postTaskStatus",
        description = "Create tasks status",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Status created successfully"),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/projects/{projectId}/tasks/statuses",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> postTaskStatus(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "PostTaskStatusRequest", description = "Request to create a task status") @Valid @RequestBody(required = false) PostTaskStatusRequest postTaskStatusRequest
    );


    /**
     * PUT /projects/{projectId}/tasks
     * Update task information
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param updateTaskRequest Request to create a task (optional)
     * @return Task updated successfully (status code 204)
     *         or There is no task with same ID or status with same ID (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "updateTask",
        description = "Update task information",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Task updated successfully"),
            @ApiResponse(responseCode = "403", description = "There is no task with same ID or status with same ID", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/projects/{projectId}/tasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateTask(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "UpdateTaskRequest", description = "Request to create a task") @Valid @RequestBody(required = false) UpdateTaskRequest updateTaskRequest
    );


    /**
     * PUT /projects/{projectId}/tasks/statuses
     * Update task status information
     *
     * @param projectId ID of a project that contains tasks (required)
     * @param taskStatusDto Request to update a task status (optional)
     * @return Task updated successfully (status code 204)
     *         or There is no status with same ID (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "updateTaskStatus",
        description = "Update task status information",
        tags = { "task" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Task updated successfully"),
            @ApiResponse(responseCode = "403", description = "There is no status with same ID", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/projects/{projectId}/tasks/statuses",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Void> updateTaskStatus(
        @Parameter(name = "projectId", description = "ID of a project that contains tasks", required = true, in = ParameterIn.PATH) @PathVariable("projectId") Long projectId,
        @Parameter(name = "TaskStatusDto", description = "Request to update a task status") @Valid @RequestBody(required = false) TaskStatusDto taskStatusDto
    );

}
