/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.solurion.eclipto.workspace.api;

import com.solurion.eclipto.workspace.dto.CreateWorkspaceRequest;
import com.solurion.eclipto.workspace.dto.ErrorDto;
import com.solurion.eclipto.workspace.dto.UpdateWorkspaceRequest;
import com.solurion.eclipto.workspace.dto.WorkspaceInfoDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "workspace", description = "the workspace API")
public interface WorkspaceApi {

    /**
     * DELETE /v1/workspaces/{workspaceId}
     * Permanently delete workspace
     *
     * @param workspaceId ID of a workspace (required)
     * @return The workspace has been deleted (status code 204)
     *         or Workspace not found (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "deleteWorkspace",
        description = "Permanently delete workspace",
        tags = { "workspace" },
        responses = {
            @ApiResponse(responseCode = "204", description = "The workspace has been deleted", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorkspaceInfoDto.class))
            }),
            @ApiResponse(responseCode = "403", description = "Workspace not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/v1/workspaces/{workspaceId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<WorkspaceInfoDto> deleteWorkspace(
        @Parameter(name = "workspaceId", description = "ID of a workspace", required = true, in = ParameterIn.PATH) @PathVariable("workspaceId") Long workspaceId
    );


    /**
     * GET /v1/workspaces/{workspaceId}
     * Get full workspace info
     *
     * @param workspaceId ID of a workspace (required)
     * @return The workspace has been found (status code 200)
     *         or Workspace not found (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "getWorkspaceInfo",
        description = "Get full workspace info",
        tags = { "workspace" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The workspace has been found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorkspaceInfoDto.class))
            }),
            @ApiResponse(responseCode = "403", description = "Workspace not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/v1/workspaces/{workspaceId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<WorkspaceInfoDto> getWorkspaceInfo(
        @Parameter(name = "workspaceId", description = "ID of a workspace", required = true, in = ParameterIn.PATH) @PathVariable("workspaceId") Long workspaceId
    );


    /**
     * POST /v1/workspaces
     * Create workspace with required information
     *
     * @param createWorkspaceRequest Request to create a workspace (optional)
     * @return Workspace created successfully (status code 201)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "postWorkspace",
        description = "Create workspace with required information",
        tags = { "workspace" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Workspace created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorkspaceInfoDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/v1/workspaces",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<WorkspaceInfoDto> postWorkspace(
        @Parameter(name = "CreateWorkspaceRequest", description = "Request to create a workspace") @Valid @RequestBody(required = false) CreateWorkspaceRequest createWorkspaceRequest
    );


    /**
     * PUT /v1/workspaces/{workspaceId}
     * Update workspace infor
     *
     * @param workspaceId ID of a workspace (required)
     * @param updateWorkspaceRequest Request to update a workspace (optional)
     * @return Workspace info updated successfully (status code 204)
     *         or There is no workspace with same ID (status code 403)
     *         or Unexpected error (status code 200)
     */
    @Operation(
        operationId = "updateWorkspaceInfo",
        description = "Update workspace infor",
        tags = { "workspace" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Workspace info updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = WorkspaceInfoDto.class))
            }),
            @ApiResponse(responseCode = "403", description = "There is no workspace with same ID", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            }),
            @ApiResponse(responseCode = "default", description = "Unexpected error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/v1/workspaces/{workspaceId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<WorkspaceInfoDto> updateWorkspaceInfo(
        @Parameter(name = "workspaceId", description = "ID of a workspace", required = true, in = ParameterIn.PATH) @PathVariable("workspaceId") Long workspaceId,
        @Parameter(name = "UpdateWorkspaceRequest", description = "Request to update a workspace") @Valid @RequestBody(required = false) UpdateWorkspaceRequest updateWorkspaceRequest
    );

}
