server:
  port: 8080

auth:
  jwt:
    issuer: http://localhost:8080
    period:
      days: 7
      hours: 10

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: "user-service"