version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_DB: eclipto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bestproject
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
  user:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - JWK_KID
      - JWKS_URL
      - FRONTEND_ORIGIN
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
  task:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: task
    ports:
      - "8081:8081"
    networks:
      - backend
    depends_on:
      - postgres
      - user
    environment:
      - JWK_KID
      - JWKS_URL
      - FRONTEND_ORIGIN
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
  project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: project
    ports:
      - "8082:8082"
    networks:
      - backend
    depends_on:
      - postgres
      - user
    environment:
      - JWK_KID
      - JWKS_URL
      - FRONTEND_ORIGIN
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: workspace
    ports:
      - "8083:8083"
    networks:
      - backend
    depends_on:
      - postgres
      - user
    environment:
      - JWK_KID
      - JWKS_URL
      - FRONTEND_ORIGIN
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD

networks:
  backend:

volumes:
  pgdata:
